app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/core/urls.py
from django.urls import path

# core
from .views import budgets_list, budget_detail
from .views import BudgetCreateView

app_name = 'core'
urlpatterns = [
    path('', budgets_list, name='budgets_list'),
    path('add', BudgetCreateView.as_view(), name='add_budget'),
    path('<slug:budget_slug>', budget_detail, name='budget_detail')
]

app/core/models.py
from django.db import models
from django.utils.text import slugify


class Budget(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    base = models.IntegerField()
    active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Budget, self).save(*args, **kwargs)

    def base_left(self):
        expense_list = Expense.objects.filter(budget=self)
        total_amount = 0
        for expense in expense_list:
            total_amount += expense.amount
        return self.base - total_amount

    def total_transactions(self):
        return Expense.objects.filter(budget=self).count()

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Expense(models.Model):
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    amount = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    attachment = models.FileField()
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

app/core/forms.py
# django
from django import forms


class ExpenseForm(forms.Form):
    title = forms.CharField()
    amount = forms.IntegerField()
    category = forms.CharField()

app/core/views.py
# python
import json

# django
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import CreateView
from django.utils.text import slugify

# core
from .models import Budget, Category, Expense
from .forms import ExpenseForm


def budgets_list(request):
    list_budgets =  Budget.objects.filter(active=True)
    return render(request, 'core/budgets_list.html', {'budgets_list':list_budgets})


def budget_detail(request, budget_slug):
    budget = get_object_or_404(Budget, slug=budget_slug)
    if request.method == 'GET':
        expenses = budget.expense_set.filter(confirmed=False)
        categories_list = Category.objects.filter(active=True)
        return render(request, 'core/budget_detail.html',{
            'budget': budget,
            'expenses_list': expenses,
            'categories_list': categories_list
        })
    elif request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            amount = form.cleaned_data['amount']
            category_name = form.cleaned_data['category']

            category =  get_object_or_404(Category, name=category_name)
            Expense.objects.create(
                budget=budget,
                title=title,
                amount=amount,
                category=category
            ).save()
    elif request.method == 'DELETE':
        id = json.loads(request.body)['id']
        expense = get_object_or_404(Expense, id=id)
        expense.delete()

        return HttpResponse('ok')

    return HttpResponseRedirect(budget_slug)


class BudgetCreateView(CreateView):
    model = Budget
    template_name = 'core/add_budget.html'
    fields = ('name', 'base')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()

        categories = self.request.POST['categoriesString'].split(',')
        for category_name in categories:
            category, _ = Category.objects.get_or_create(
                name = category_name
            )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return slugify(self.request.POST['name'])

app/core/templates/core/add_budget.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <label for="categoryInput">Expense Categories (hit enter after every category)</label>
            <input type="text" name="categoryInput" id="categoryInput">
            <input type="hidden" name="categoriesString">

            <ul id="categoriesContainer">

            </ul>
            <button type="submit" class="btn">Start Budget</button>
        </form>
    </div>

    <script src="{% static 'js/script.js' %}"></script>
{% endblock content %}

app/core/templates/core/budget_detail.html
{% extends 'base/base.html' %}
{% block title %}Budget Detail{% endblock title %}
{% block content %}
    <div class="container">
        <section class="section section-stats">
            <div class="row">
                <div class="col s12 m12 l4">
                    <div class="card-panel">
                        <h6 class="bold">Total Budget</h6>
                        <h1 class="bold">$ {{ budget.base }}</h1>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card-panel">
                        <h6 class="bold">Budget Left</h6>
                        {% if budget.base_left > 0 %}
                            <h1 class="bold green-text">$ {{ budget.base_left }}</h1>
                        {% elif budget.base_left == 0 %}
                            <h1 class="bold orange-text">$ {{ budget.base_left }}</h1>
                        {% else %}
                            <h1 class="bold red-text">$ {{ budget.base_left }}</h1>
                        {% endif %}
                    </div>
                </div><div class="col s12 m6 l4">
                    <div class="card-panel">
                        <h6 class="bold">Total Transactions</h6>
                        <h1 class="bold">{{ budget.total_transactions }}</h1>
                    </div>
                </div>
            </div>
        </section>
        <section class="section section-expenses">
            <div class="row">
                <button class="btn waves-effect right modal-trigger" href="#expenseModal">
                    <i class="material-icons white-text left">add_circle</i>
                    Add Expense
                </button>
            </div>
            <ul class="z-depth-1">
                {% for expense in expenses_list %}
                    <li>
                    <div class="card-panel z-depth-0 expense">
                        <div class="row">
                            <div class="col l6">
                                <span class="title">
                                    {{ expense.title }}
                                </span>
                            </div>
                            <div class="col l3">
                                <span class="title">
                                    $ {{ expense.amount }}
                                </span>
                            </div>
                            <div class="col 1">
                                <span class="title bold">
                                    {{ expense.category.name }}
                                </span>
                            </div>
                            <a class="close-icon" onclick="deleteExpense(this)" data-id="{{ expense.id }}">
                                <i class="material-icons red-text right">close</i>
                            </a>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </section>
    </div>

    <div id="expenseModal" class="modal">
        <div class="modal-content">
            <h4>Add Expense</h4>

            <form method="POST">
                {% csrf_token %}
                <label for="title">Title</label>
                <input name="title" id="tittle">

                <label for="amount">Amount</label>
                <input name="amount" id="tamount">

                <select name="category">
                    {% for category in categories_list %}
                        <option>{{ category.name }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn">Add</button>
            </form>
        </div>
    </div>

    <script>
        var elem = document.querySelector('.modal');
        var instance = M.Modal.init(elem);

        var elem = document.querySelector('select');
        var instance = M.FormSelect.init(elem);

        function deleteExpense(e){
            let id = e.dataset.id
            e.closest('li').remove()
            fetch('',{
                method: 'DELETE',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({
                    'id': id
                }),
                credentials: 'same-origin',
            });
            location.reload();
        }
    </script>
{% endblock content %}

app/core/templates/core/budgets_list.html
{% extends 'base/base.html' %}
{% block title %}Budgets list{% endblock title %}
{% block content %}
    <div class="container">
        <h1>Active Budgtes</h1>
        <hr>
        <div class="row">
            {% for budget in budgets_list %}
                <div class="col s12 l3">
                    <div class="card-panel">
                        <h5>{{ budget.name }}</h5>
                        <a href="{% url 'core:budget_detail' budget.slug %}" class="btn">Go</a>
                    </div>
                </div>
            {% empty %}
                <div class="container">
                    <div class="nobudget-wraper center">
                        <h3 class="gray-text">
                            Sorry, you don't have any budget, yet.
                        </h3>
                        <a href="" class="btn-large grey">
                            <i class="material-icons white-text left">add_circle</i>
                            <span class="bold">Add Budget</span>
                        </a>
                    </div>
                </div>
            {%  endfor %}
        </div>
    </div>
{% endblock content %}

app/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Base{% endblock title %}</title>
    <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block extarstatic %}{% endblock extarstatic %}
</head>
<body>
    {% block content %}
    {% endblock content %}

    {% block extajs %}{% endblock extajs %}
</body>
</html>